# Generated by Django 5.2.11 on 2026-02-09 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('orgName', models.CharField(max_length=255)),
                ('orgPAN', models.CharField(max_length=50)),
                ('orgAddress', models.TextField()),
                ('incorpNo', models.CharField(blank=True, default='', max_length=100)),
                ('incorpDate', models.CharField(blank=True, default='', max_length=20)),
                ('businessNature', models.CharField(max_length=255)),
                ('gstNumber', models.CharField(blank=True, default='', max_length=100)),
                ('billingAddress', models.TextField()),
                ('tanNumber', models.CharField(blank=True, default='', max_length=100)),
                ('orgEmail', models.CharField(max_length=255)),
                ('orgWebsite', models.CharField(blank=True, default='', max_length=255)),
                ('orgContact', models.CharField(max_length=50)),
                ('orgAltContact', models.CharField(blank=True, default='', max_length=50)),
                ('authName', models.CharField(max_length=255)),
                ('authPAN', models.CharField(max_length=50)),
                ('authDesignation', models.CharField(max_length=255)),
                ('authDOB', models.CharField(max_length=20)),
                ('authMobile', models.CharField(max_length=50)),
                ('authEmail', models.CharField(max_length=255)),
                ('authNationality', models.CharField(max_length=100)),
                ('correspondenceAddress', models.TextField()),
                ('authLetter', models.BooleanField(default=False)),
                ('idProof', models.BooleanField(default=False)),
                ('authPanFront', models.ImageField(blank=True, null=True, upload_to='applications/auth_pan/')),
                ('authPanBack', models.ImageField(blank=True, null=True, upload_to='applications/auth_pan/')),
                ('authAadhaarFront', models.ImageField(blank=True, null=True, upload_to='applications/auth_aadhaar/')),
                ('authAadhaarBack', models.ImageField(blank=True, null=True, upload_to='applications/auth_aadhaar/')),
                ('services_csv', models.TextField(blank=True, default='')),
                ('digitalRequirements', models.BooleanField(default=False)),
                ('digitalNotes', models.BooleanField(default=False)),
                ('communicationCompliance', models.BooleanField(default=False)),
                ('termsAgreement', models.BooleanField(default=False)),
                ('applicantName', models.CharField(max_length=255)),
                ('applicantDate', models.CharField(max_length=20)),
                ('applicantSignatureFile', models.ImageField(blank=True, null=True, upload_to='applications/signatures/')),
                ('companySignatory', models.CharField(blank=True, default='', max_length=255)),
                ('companyDate', models.CharField(blank=True, default='', max_length=20)),
                ('companySignatureFile', models.ImageField(blank=True, null=True, upload_to='applications/signatures/')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Click Connect Media Pvt. Ltd.', max_length=255)),
                ('signature_image', models.ImageField(blank=True, null=True, upload_to='company/signatures/')),
            ],
        ),
    ]
