# Generated by Django 5.2.11 on 2026-02-10 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clintonboardingbe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='stamp_image',
            field=models.ImageField(blank=True, null=True, upload_to='company/stamps/'),
        ),
    ]
